-- MySQL Script generated by MySQL Workbench
-- ter 05 mai 2020 09:41:49 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estacioPro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estacioPro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estacioPro` DEFAULT CHARACTER SET utf8 ;
USE `estacioPro` ;

-- -----------------------------------------------------
-- Table `estacioPro`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacioPro`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nick_name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacioPro`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacioPro`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telephone` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk_contact_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_contact_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `estacioPro`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
